# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/tasne/Downloads/cpp-course-autumn-2022/Module_5/T2-polynomial

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/tasne/Downloads/cpp-course-autumn-2022/Module_5/T2-polynomial

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/tasne/Downloads/cpp-course-autumn-2022/Module_5/T2-polynomial/CMakeFiles /mnt/c/Users/tasne/Downloads/cpp-course-autumn-2022/Module_5/T2-polynomial/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/tasne/Downloads/cpp-course-autumn-2022/Module_5/T2-polynomial/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named T2-polynomial

# Build rule for target.
T2-polynomial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 T2-polynomial
.PHONY : T2-polynomial

# fast build rule for target.
T2-polynomial/fast:
	$(MAKE) -f CMakeFiles/T2-polynomial.dir/build.make CMakeFiles/T2-polynomial.dir/build
.PHONY : T2-polynomial/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/T2-polynomial.dir/build.make CMakeFiles/T2-polynomial.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/T2-polynomial.dir/build.make CMakeFiles/T2-polynomial.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/T2-polynomial.dir/build.make CMakeFiles/T2-polynomial.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/poly.o: src/poly.cpp.o

.PHONY : src/poly.o

# target to build an object file
src/poly.cpp.o:
	$(MAKE) -f CMakeFiles/T2-polynomial.dir/build.make CMakeFiles/T2-polynomial.dir/src/poly.cpp.o
.PHONY : src/poly.cpp.o

src/poly.i: src/poly.cpp.i

.PHONY : src/poly.i

# target to preprocess a source file
src/poly.cpp.i:
	$(MAKE) -f CMakeFiles/T2-polynomial.dir/build.make CMakeFiles/T2-polynomial.dir/src/poly.cpp.i
.PHONY : src/poly.cpp.i

src/poly.s: src/poly.cpp.s

.PHONY : src/poly.s

# target to generate assembly for a file
src/poly.cpp.s:
	$(MAKE) -f CMakeFiles/T2-polynomial.dir/build.make CMakeFiles/T2-polynomial.dir/src/poly.cpp.s
.PHONY : src/poly.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... T2-polynomial"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/poly.o"
	@echo "... src/poly.i"
	@echo "... src/poly.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

